### PR TITLE
Support build in Windows

### LINKED ISSUE #63: Installation on Windows 10
All goes well (after install VS2017 SDKs), except for "pip install ffcv".  Both versions are tested and yields:

```
(ffcv) C:\Users\Nico Stuurman>pip install ffcv
Collecting ffcv
  Using cached ffcv-0.0.2.tar.gz (53 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\miniconda3\envs\ffcv\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nico Stuurman\\AppData\\Local\\Temp\\pip-install-6g53gzac\\ffcv_bec63284499b4f4eaef3c59145fdfa37\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nico Stuurman\\AppData\\Local\\Temp\\pip-install-6g53gzac\\ffcv_bec63284499b4f4eaef3c59145fdfa37\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Nico Stuurman\AppData\Local\Temp\pip-pip-egg-info-2f42xkgr'
       cwd: C:\Users\Nico Stuurman\AppData\Local\Temp\pip-install-6g53gzac\ffcv_bec63284499b4f4eaef3c59145fdfa37\
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Nico Stuurman\AppData\Local\Temp\pip-install-6g53gzac\ffcv_bec63284499b4f4eaef3c59145fdfa37\setup.py", line 30, in <module>
      extension_kwargs = pkgconfig('opencv4', extension_kwargs)
    File "C:\Users\Nico Stuurman\AppData\Local\Temp\pip-install-6g53gzac\ffcv_bec63284499b4f4eaef3c59145fdfa37\setup.py", line 18, in pkgconfig
      raise Exception()
  Exception
```

Not sure where the logs are, but surely would expect 'pkgconfig' to be absent on Windows.

Any ideas?

### PR DESCRIPTION
**Pull request by kynk94**
Resolves #63

Add package finding process in `setup.py`.
And modifying `ffcv/libffcv.py, libffcv/libffcv.cpp` to import ffcv without error.

My 2 windows pc works without error, but I think need others test.
And I didn't test in linux.

### CODE REVIEW

**Comment by GuillaumeLeclerc** [comment]
Hi! did the unit tests passed ?

We had issues with the MacOS port as the `pread` seem to have different signature there

**Comment by kynk94** [comment]
I just did unit test, and it failed. Above test means build and import ffcv components.

pytest give error when iterating `Loader` in [tests\test_array_field.py](https://github.com/libffcv/ffcv/blob/main/tests/test_array_field.py#L58)
The error was occurred when call **numba jit compiled code** to get results.
https://github.com/libffcv/ffcv/blob/main/ffcv/loader/epoch_iterator.py#L134
The **code** is `CPUDispatcher(<function stage_0 at 0x0000023F941B43A0>)` instance

The error is below, but there is no detailed traceback.
So there is a problem with debugging and need more time.
```
Windows fatal exception: access violation

Current thread 0x00003cdc (most recent call first):
  File "c:\users\user\miniconda3\lib\site-packages\ffcv\loader\epoch_iterator.py", line 134 in run_pipeline
  File "c:\users\user\miniconda3\lib\site-packages\ffcv\loader\epoch_iterator.py", line 80 in run
  File "c:\users\user\miniconda3\lib\threading.py", line 932 in _bootstrap_inner
  File "c:\users\user\miniconda3\lib\threading.py", line 890 in _bootstrap
```

**Comment by GuillaumeLeclerc** [comment]
My guess is that its might be related to `pread` but I don't know how else I can help you :/

**Comment by kynk94** [comment]
Thanks. Concentrating on `pread` and debugging, it seems that your guess is correct.
I'll try to figure out how to use file read by `ctypes` correctly on Windows.

**Comment by kynk94** [comment]
All bugs resolved, and **passed all unit test**.
I skipped `test_memory_leak.py` because DatasetWriter does not have `write_pytorch_dataset` method .
And in `test_rrc.py`, when mode is 'jpg', assert is not always True, so I compared it with the results on linux and it seemed to match.

Since all tests passed, `cdll.msvcrt._read` behaves exactly the same as `pread`.

And there is one more minor issue.
If the size of the written dataset by DatasetWriter is less than **16MB**, it will take a very long time.
I don't know why.

**Comment by GuillaumeLeclerc** [comment]
@kynk94 Do you think this could be merged into v1.0 ? Would you be willing to test it when I make a release candidate ?

**Comment by kynk94** [comment]
yes it could be merged if there is no problem on linux with this PR's logic.
And I can test it with my windows desktop because the test process is simple.

**Comment by GuillaumeLeclerc** [comment]
Looks very good to me. I'm merging into v1.0.0. Thank you so much @kynk94 I hope it's going to be useful to many people :smiley:

**Pull request merged**
