### PR TITLE
Change JIT assertion to a setter to allow for tensor augmentations before JIT ones

### PR DESCRIPTION
**Pull request by andrewilyas**
Also removed some unused imports, all tests passing

### CODE REVIEW

**Comment by GuillaumeLeclerc** [comment]
@andrewilyas Do we need to change these assertions for other transforms ?

**Comment by andrewilyas** [comment]
I believe they should now be removed for all transforms. Would still wait before merging this in though, will write some corresponding tests.

**Comment by GuillaumeLeclerc** [comment]
Was it merged in 0.0.3 ? @andrewilyas

**Comment by andrewilyas** [comment]
@GuillaumeLeclerc merging!

**Pull request merged**
